import type { GetServerSideProps, NextPage } from 'next'
import Router from 'next/router'
import Head from 'next/head'
import PostComponent from "../components/Post"
import { Post, GetPostResults } from '../types'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage<{posts: Post[]}> = ({posts}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Meet Rocket.rs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick = {() => Router.push("/create-post")}>Create Post</button>
      <button onClick = {() => Router.push("/unpublished")}>View Unpublished Post</button>
      {posts.map(post => (
          <PostComponent key={post.id} posts={post}/>
      ))}  

    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
   const res = await fetch("http://127.0.0.1:8000/api/get-posts")
   const  results: GetPostResults  = await res.json()

   return {
    props: {
      posts: results
    }
   }
}
export default Home
