import React from 'react'
import type { GetServerSideProps, NextPage } from 'next'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import PostComponent from "../components/Post"
import { Post, GetPostResults } from '../types'

const Unpublished: NextPage<{posts: Post[]}>= ({posts}) => {
  return (
    <div className={styles.container}>
        <Head>
        <title>Next.js Meet Rocket.rs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        {posts.map(post => (
            <PostComponent key={post.id} posts={post}/>
        ))}  
  </div>
  )
}


export const getServerSideProps: GetServerSideProps = async (context) => {
   const res = await fetch("http://127.0.0.1:8000/api/get-posts?unpublished=true")
   const  results: GetPostResults  = await res.json()

   return {
    props: {
      posts: results
    }
   }
}

export default Unpublished
